name: First time PR created
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - 'release/**'
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/no-trigger.yml
    with:
      lane: fastlane increase_build_number number:$GITHUB_RUN_NUMBER