name: Every commit push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, ARM64]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Cache modules
        id: cache-module
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: new.txt
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('new.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('new.txt') }}

      - if: ${{ steps.cache-module.outputs.cache-hit != 'true' }}
        name: Generate test.sh
        continue-on-error: true
        run: |
          ls
          ./test.sh
          echo "not here august"
          ls

      - name: Run fastlane
        run: |
          fastlane custom_lane
      - run: |
          echo "🍏 This job's status is ${{ job.status }}. ${{github.run_number}}"
          echo ENV["BUILD_NUMBER"]
      - name: List new content
        run: |
          cat new.txt
    
