name: Hello world
run-name: triggered manually by ${{ github.actor }}
on: [push]
jobs: 
  hello_world_job:
    runs-on: [self-hosted, ARM64]
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions/hello-action.yml
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash